version: "3.7"

services:
  timelog-db:
    hostname: timelog-db
    image: postgres:13
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "timelog" ]
      timeout: 15s
      interval: 5s
      retries: 5
    restart: always
    environment:
      - POSTGRES_USER=timelog
      - POSTGRES_PASSWORD=${TIMELOGDBPW}
      - POSTGRES_DB=timelog
    ports:
      - 5472:5432
    volumes:
      - /volume1/docker/timelog-db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
  timelog-service:
    hostname: timelog-service
    image: johanwannheden/timelog-service:latest
    environment:
      - QUARKUS_PROFILE=prod
      - JAVA_ENABLE_DEBUG=true
      - TIMELOGDBPW=${TIMELOGDBPW}
    ports:
      - 9443:9443
  timelog-client:
    hostname: timelog-client
    image: johanwannheden/timelog:latest
    ports:
      - 4200:4200
